### Question 1

In [12]:
import numpy as np
def matrixAdd(A,B):
    rows = len(A)
    cols = len(A[0])
    result = np.zeros((rows,cols))
    for i in range(rows):
        for j in range(cols):
            result[i][j] = A[i][j] + B[i][j]
    return result

In [13]:
X = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]
 
Y = [[9,8,7],
    [6,5,4],
    [3,2,1]]

In [14]:
matrixAdd(X,Y)

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

### Question 2

In [23]:
def matrixMulti(A,B):
    rowsA = len(A)
    colsA = len(A[0])
    rowsB = len(B)
    colsB = len(B[0])
    result = np.zeros((rowsA,colsB))
    if (colsA == rowsB):
        for i in range(rowsA):
            for j in range(colsB):
                for k in range(rowsB):
                    result[i][j] += A[i][k]*B[k][j]
    return result

In [24]:
matrixMulti(X,Y)

array([[ 30.,  24.,  18.],
       [ 84.,  69.,  54.],
       [138., 114.,  90.]])

### Question 3

In [28]:
def matrixTranspose(A):
    rows = len(A)
    cols = len(A[0])
    transpose = np.zeros((cols,rows))
    for i in range(rows):
        for j in range(cols):
            transpose[i][j] = A[j][i]
    return transpose

In [29]:
matrixTranspose(X)

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

### Question 4

In [46]:
def sortWords(string):
    words = string.split()
    result = words.sort()
    for word in result:
        return word

In [47]:
sortWords('My name is Manasa')

TypeError: 'NoneType' object is not iterable

### Question 5

In [56]:
import re
def removePunc(string):
    res = re.sub(r'[^\w\s]', '', string)
    return res

In [57]:
removePunc("Hello!!!, he said ---and went.")

'Hello he said and went'